version: '3.7'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: labamoon/taski_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  frontend:
    image: labamoon/taski_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: labamoon/taski_gateway:latest
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80